app = "yt-autostream-flyio"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "docker.io/library/debian:latest"

[env]
  YOUTUBE_STREAM_KEY = ""

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
